import { CRAWL_RUN_STATUSES } from '@cre/shared';
import { randomUUID } from 'node:crypto';
import type { FastifyInstance } from 'fastify';
import { z } from 'zod';

import { createAuthGuards } from '../auth/hooks';
import { ApiError } from '../errors';
import { enumCsv } from '../params';
import { parsePageQuery } from '../pagination';
import type { AppDeps } from '../ports';

const triggerSchema = z
  .object({
    sourceKey: z.string().min(1),
    urls: z.array(z.string().url()).min(1).max(100).optional(),
  })
  .strict();

/** Source-config fallback for entry URLs (validated to actual strings). */
function entryUrlsFromConfig(config: Record<string, unknown>): string[] {
  const raw = config['entryUrls'];
  if (!Array.isArray(raw)) return [];
  return raw.filter(
    (value): value is string => typeof value === 'string' && value.trim() !== '',
  );
}

export function registerCrawlRunRoutes(app: FastifyInstance, deps: AppDeps): void {
  const guards = createAuthGuards(deps.sessions, deps.now);

  app.get('/crawl-runs', { preHandler: guards.requireAuth }, async (request) => {
    const query = request.query as Record<string, unknown>;
    const { page, pageSize } = parsePageQuery(query);
    const sourceKeyRaw = query['sourceKey'];
    const sourceKey =
      typeof sourceKeyRaw === 'string' && sourceKeyRaw.trim() !== ''
        ? sourceKeyRaw.trim()
        : undefined;
    const statuses = enumCsv(query['status'], CRAWL_RUN_STATUSES, 'status');
    return deps.crawlRuns.list({ sourceKey, statuses }, page, pageSize);
  });

  /** Run detail — includes errors so operators can inspect and recover failures. */
  app.get('/crawl-runs/:id', { preHandler: guards.requireAuth }, async (request) => {
    const { id } = request.params as { id: string };
    const run = await deps.crawlRuns.findById(id);
    if (!run) {
      throw ApiError.notFound('NOT_FOUND', `no crawl run with id '${id}'`);
    }
    return run;
  });

  /**
   * Operator action: trigger a crawl.
   *
   * Two valid modes:
   *
   * 1) Synchronous execution (when async infrastructure is not configured):
   *    The crawl runs to completion in the HTTP request and the result is
   *    returned directly.  This path is kept for rapid development and
   *    environments that do not have a running worker.
   *
   * 2) Asynchronous / queued execution (the recommended production path):
   *    A crawl_run record is created with status 'queued', an outbox event
   *    is inserted, and the HTTP response returns 202 Accepted.  A background
   *    worker picks up the outbox record, executes the crawler via the
   *    same @cre/crawler engine, and updates the crawl run when done.
   *
   * The mode is selected at runtime by the presence of the Redis-backed
   * outbox implementation.  When the outbox is available, path 2 is used
   * automatically.  When it is not (e.g. no REDIS_URL), path 1 is used so
   * the API still functions.
   *
   * Invariant: regardless of mode, a crawl_run record always exists and
   * is recoverable — the outbox pattern guarantees that a queued run will
   * eventually have a corresponding job or be visibly recoverable as an
   * unpublished outbox record.
   */
  app.post(
    '/crawl-runs',
    { preHandler: guards.requireRole('operator', 'admin') },
    async (request) => {
      const body = triggerSchema.parse(request.body);
      const source = await deps.sources.findByKey(body.sourceKey);
      if (!source) {
        throw ApiError.notFound('NOT_FOUND', `no source with key '${body.sourceKey}'`);
      }
      if (!deps.crawl.hasAdapter(source.key)) {
        throw ApiError.badRequest(
          'NO_ADAPTER',
          `no adapter registered for source '${source.key}'`,
        );
      }
      const urls = body.urls ?? entryUrlsFromConfig(source.config);
      if (urls.length === 0) {
        throw ApiError.badRequest(
          'NO_URLS',
          `no entry URLs: pass 'urls' in the request or configure 'entryUrls' on the source`,
        );
      }

      // ── Build the crawl payload for the job ────────────────────────
      const now = deps.now ?? ((): Date => new Date)();
      const correlationId = /* uuidv4() */; // will be generated by DB

      // ── Use outbox pattern when available; fall back to sync crawl ──
      if (deps.outbox) {
        // Path 2: async queued execution
        const runId = await deps.crawlRuns.createQueued({
          sourceId: source.id,
          requestedAt: now(),
          requestedByUserId: request.user!.id,
          urls,
        });

        await deps.outbox.create(
          'crawl.run',
          {
            crawlRunId: runId,
            sourceId: source.id,
            requestedByUserId: request.user!.id,
            requestedAt: now().toISOString(),
          },
          runId,
        );

        // Emit audit event
        await deps.audit.append({
          action: 'crawl.queued',
          at: now(),
          actorUserId: request.user!.id,
          actorEmail: request.user!.email,
          targetType: 'source',
          targetId: source.key,
          metadata: { urlCount: urls.length, runId },
        }).catch((error: unknown) => request.log.error({ error }, 'audit append failed'));

        return {
          crawlRun: {
            id: runId,
            status: 'queued',
          },
        };
      }

      // Path 1: synchronous execution (no async infra)
      const outcome = await deps.crawl.trigger(source, urls);

      await deps.audit
        .append({
          action: 'crawl.triggered',
          at: now(),
          actorUserId: request.user!.id,
          actorEmail: request.user!.email,
          targetType: 'source',
          targetId: source.key,
          metadata: { urlCount: urls.length },
        })
        .catch((error: unknown) => request.log.error({ error }, 'audit append failed'));

      return outcome;
    },
  );
}