-- Migration 0007: transactional outbox + worker execution fields.
--
-- outbox — job queue written in the same transaction as the crawl run, so a
--   persisted queued run either gets a queue job or is visibly recoverable as
--   an unpublished record. `type` allows reuse for CSV exports, notifications,
--   CRM sync, and SLA checks.
-- crawl_runs.urls / requested_by_user_id / worker_id — persisted crawl
--   parameters, who triggered the run, and the idempotency claim that stops two
--   workers executing the same run.
--
-- Regenerated by `npm run db:generate -w packages/db`: the previous hand-written
-- 0007/0008 files were never listed in meta/_journal.json and were therefore
-- never applied by `npm run db:migrate` (the migrator reads only journal entries).
-- If an environment applied those files by hand, the statements below will fail
-- as "already exists" — clear the leftover objects or mark this migration applied.
CREATE TABLE "outbox" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"type" text NOT NULL,
	"payload" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"last_error" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"started_at" timestamp,
	"completed_at" timestamp,
	"correlation_id" uuid
);
--> statement-breakpoint
ALTER TABLE "crawl_runs" ADD COLUMN "urls" jsonb DEFAULT '[]'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "crawl_runs" ADD COLUMN "requested_by_user_id" uuid;--> statement-breakpoint
ALTER TABLE "crawl_runs" ADD COLUMN "worker_id" text;--> statement-breakpoint
CREATE INDEX "outbox_status_created_idx" ON "outbox" USING btree ("status","created_at");--> statement-breakpoint
CREATE INDEX "outbox_correlation_idx" ON "outbox" USING btree ("correlation_id");--> statement-breakpoint
ALTER TABLE "crawl_runs" ADD CONSTRAINT "crawl_runs_requested_by_user_id_users_id_fk" FOREIGN KEY ("requested_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "crawl_runs_requested_by_idx" ON "crawl_runs" USING btree ("requested_by_user_id");